### ISSUE TITLE
Replace Operation.operationName usage with Operation.kind

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/urql-devtools-exchange#105]
See deprecation notes here: https://github.com/FormidableLabs/urql/discussions/1098
And: https://github.com/FormidableLabs/urql/pull/1045

All instances of `operation.operationName` simply need to be changed to `operation.kind` and the peer dependency on `@urql/core` needs to be bumped to `>=1.14.0`.

**Comment by andyrichardson** [comment]
Fixed by #108
