### ISSUE TITLE
Anything special to get this working in Expo?

### ISSUE THREAD

**Issue by GollyJer** [FormidableLabs/urql-devtools-exchange#109]
Hi, first time user here.
I've got urql set up and working great in a react-native Expo project. 
However, when I debug remote-js in the browser and access the urql tab I see this.

<img src=https://user-images.githubusercontent.com/689204/101233976-9b9e1e00-3670-11eb-8df0-a5a554f27304.png width=250>

I'm also a little confused by this part of the instructions.

<img src=https://user-images.githubusercontent.com/689204/101234036-10715800-3671-11eb-821a-6628cd8b72b4.png width=350>

What's "the electron app"?

Thanks!

**Comment by andyrichardson** [comment]
Hey @GollyJer, I'm going to close this in favor of https://github.com/FormidableLabs/urql-devtools/issues/324
