### ISSUE TITLE
Installing Devtools exchange doesnt work as expected

### ISSUE THREAD

**Issue by theianjones** [FormidableLabs/urql-devtools-exchange#12]
I have installed the devtools like the readme suggests. Heres my example project:

https://github.com/theianjones/screencasts/blob/73888e4ad164cc82ff36b98af89c5b29c4212015/content/playlists/intro-to-urql/urql-dev-tools/src/index.js#L1-L20

The exchange code is in `index.js` and my query is in `App.js`.

I get this error when I inspect the devtools panel:
![image](https://user-images.githubusercontent.com/4407263/65911355-878acc80-e39a-11e9-9e50-74071191caf4.png)

Am I doing something wrong? Can you help me out?

**Comment by JoviDeCroock** [comment]
Hey,

The devtools extension version is not compatible with your exchange version. We have published our new extension some weeks ago but it hasn't been approved yet. Sorry for the inconvenience this may cause.

**Comment by theianjones** [comment]
Hey @JoviDeCroock, Thanks for the quick response. What version do i need to download?

**Comment by JoviDeCroock** [comment]
0.0.3 or 0.1.0-beta.0, could you tell me if one of those works? Thanks in advance.

**Comment by andyrichardson** [comment]
@theianjones I'm assuming this is now resolved - drop a comment if that is not the case :+1:
