### ISSUE TITLE
Conditions for Chrome extension / devtoolsExchange init

### ISSUE THREAD

**Issue by nephix** [FormidableLabs/urql-devtools-exchange#127]
Hey,

what are the conditions for the Chrome extension to pick up the `devtoolsExchange` correctly?

On our website I only see:

> Waiting for exchange
> Make sure you're using the Urql Devtools exchange!

but it never seems to be able to connect with the urql client.

I use:
- `@urql/preact`
- `@urql/devtools`
- `devtoolsExchange` is first in `exchanges`
- the website loads an embed script which initializes web components
- urql client(s) get initialized within web components

In the source code I saw that the connection between urql client and urql devtools works via `window.postMessage`, so web components shouldn't be the hurdle

**Comment by andyrichardson** [comment]
Hey @nephix!

Just to be sure there isn't anything odd going on in your browser, try opening the devtools panel on [this page](https://urql-devtools-exchange.netlify.app/). If that works, we can rule out any browser specific issues.

**Comment by nephix** [comment]
@andyrichardson it works there, and now also in our project.

The issue was that we have multiple urql clients on 1 page, so we only added the `devtoolsExchange` to one instance of urql instead of to all

**Comment by andyrichardson** [comment]
Thanks for the update! In that case I'll close this
