### ISSUE TITLE
urql devtools when page is inside an iframe

### ISSUE THREAD

**Issue by johnjiang** [FormidableLabs/urql-devtools-exchange#98]
Is there anyway to enable the devtools when the page is inside an iframe?

**Comment by wgolledge** [comment]
Hi @johnjiang, this should definitely be possible! I think it's likely an issue that needs to be resolved within the [urql-devtools](https://github.com/FormidableLabs/urql-devtools) repo as opposed to here. Going to close this ticket in favour of the [recreated issue there](https://github.com/FormidableLabs/urql-devtools/issues/280).
